### ISSUE TITLE
Manure System 1.0.9.0 beta funktioniert auf Mac nicht

### ISSUE THREAD

**Issue by Reflax2211** [stijnwop/manureSystem#115]
Moin, 
ich habe mal eine frage, ich habe mir gestern das Manure System 1.0.9.0 beta runtergeladen und auf meinem dedi server gespielt, damit das koppeln der Schläuche für den Mod "Lager für Tierställe" für den Güllesilo klappt.  Der Mod funktioniert auf meinem Windows Rechner einwandfrei aber auf einem iMac von einem Mitspieler nicht. Er joint dem Spiel und bleibt dauerhaft im Synchronisierungsmodus. Kann mir einer helfen, und sagen woran dies liegen könnte? 

MFG René

**Comment by Snickers125** [comment]
Hey 👋🏻 I highly recommend this template 

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. Windows]
FS patch version [e.g. 1.0.0.0]
Additional context
Add any other context about the problem here.


Make sure your friend is running the same game version as you dedicated server.

**Comment by stijnwop** [comment]
Report with log and clear information + English.
