### ISSUE TITLE
manureSystem FS22

### ISSUE THREAD

**Issue by iwan4672** [stijnwop/manureSystem#160]
Will manureSystem be to FS22?.

**Comment by Move2win** [comment]
Hope this great mod could be available for FS22 too.

**Comment by Bovrinox** [comment]
Yeah I'd love this on 22, its confusing because of all the false info out there claiming this mod is already on 22, but clearly it isn't because it always takes you to links for FS19 mods.
Unfortunately I don't think it will be , since Giants is releasing DLC that is basically this mod, except it probably wont work properly since they're making it themselves XD

**Comment by derHaggie** [comment]
It isnt a giants dlc. It is a thirt party dlc from creative mesh. And maybe you should watched the farmcon stream properly ;)

**Comment by Bandesss** [comment]
Gibt's was neues dazu?

**Comment by Lch11416** [comment]
Can't wait to see it in FS22

**Comment by MaxEl3ven** [comment]
Are there any news? I miss this mod so much!

**Comment by Lch11416** [comment]
Well, not really any news, but I miss this mod so much too~ I love those house things to pump the tank, that's really fun😃

**Comment by KITT3000** [comment]
On the discord server Vertex Design shared some ss and videos from the work on this mod

**Comment by Lch11416** [comment]
That sounds good, but unfortunately I can't visit discord in my country, may I ask how's it going on? Is it nearly finished or just started?
