### ISSUE TITLE
Mods/ DLCs won't react on ManureSystem mod

### ISSUE THREAD

**Issue by Terrabey** [stijnwop/manureSystem#167]
Hello everyone 
I have tested the Manure System Mod and it is great. However I have seen some tiny issues which let me make a bit curios. 
1. Pumps and Hoes DLC: It works on their Buildings but not on their Pumps...
2. Modular BGA : Here goes nothing
3. Modular BGA PlanET and PlanET expansion for Pumps and Hoes: Same as in the upper named scenario

**Comment by Terrabey** [comment]
On Vanilla Silos this Mod doesn't work neither.

**Comment by stijnwop** [comment]
Hi,

Not sure what expectations you have, but I can't make all mods magically work. Thats up to the modder of the Modular BGA to make it compatible.

About the Pumps and **Hoses** DLC, see the 'out-of-the-box support' list in the readme of this repository. The fermenters and vehicles will follow later due to the lack of time on my side and I don't want to delay this project even more.

What vanilla silos are you referring to? The base tank with extensions are supported as you can see in the 'out-of-the-box support' list.

**Comment by Terrabey** [comment]
Hello again so Vanilla Silo was my own mistake Hause I did not look around the entire Silo.
For the Modular BGA I am looking to contact them.
